import streamlit as st
import random

# --- 1. 단어 데이터 (중복이 있어도 아래 로직이 제거해줍니다) ---
if 'voca_db' not in st.session_state:
    raw_data = {
        raw_data = {
        # [1-100] A-B 그룹
        "abandon": "버리다, 포기하다", "ability": "능력", "absorb": "흡수하다", "abstract": "추상적인",
        "academic": "학업의, 학교의", "accent": "강세, 말투", "accept": "받아들이다", "access": "접근, 이용",
        "accompany": "동행하다", "account": "계좌, 설명", "accurate": "정확한", "accuse": "비난하다, 고소하다",
        "achieve": "성취하다", "acknowledge": "인정하다", "acquire": "습득하다, 얻다", "adapt": "적응하다, 맞추다",
        "addict": "중독자, 중독시키다", "address": "주소, 다루다, 연설하다", "adequate": "적절한, 충분한", "adjust": "조절하다, 적응하다",
        "administer": "관리하다, 운영하다", "admire": "존경하다, 감탄하다", "admit": "인정하다, 허가하다", "adopt": "채택하다, 입양하다",
        "advance": "전진, 진보", "advantage": "장점, 유리함", "adventure": "모험", "advertise": "광고하다",
        "advise": "조언하다", "advocate": "옹호하다, 주장하다", "affect": "영향을 미치다", "afford": "~할 여유가 있다",
        "agency": "대행사, 기관", "agenda": "의제, 안건", "agent": "대리인, 중개인", "aggressive": "공격적인",
        "agree": "동의하다", "agriculture": "농업", "aid": "도움, 원조", "aim": "목표, 겨냥하다",
        "alarm": "경보, 놀라게 하다", "alert": "방심하지 않는, 경고하다", "alien": "외국인의, 이질적인", "align": "정렬하다",
        "alike": "비슷한, 똑같이", "alive": "살아있는", "allocate": "할당하다", "allow": "허용하다",
        "ally": "동맹국, 협력자", "alter": "변경하다, 바꾸다", "alternative": "대안, 대체 가능한", "altitude": "고도, 높이",
        "amaze": "놀라게 하다", "ambition": "야망, 포부", "amount": "양, 총계", "analyze": "분석하다",
        "ancestor": "조상, 선조", "anchor": "닻, 고정시키다", "ancient": "고대의, 아주 오래된", "announce": "발표하다",
        "annoy": "짜증나게 하다", "annual": "매년의, 연례의", "anticipate": "예상하다, 기대하다", "anxiety": "불안, 걱정",
        "apology": "사과", "apparent": "명백한, 외견상의", "appeal": "호소하다, 매력", "appear": "나타나다",
        "appetite": "식욕, 욕구", "apply": "적용하다, 지원하다", "appoint": "임명하다, 정하다", "appreciate": "감사하다, 가치 인정",
        "approach": "접근하다", "appropriate": "적절한", "approve": "승인하다", "approximate": "대략의",
        "architect": "건축가", "area": "지역, 영역", "argue": "주장하다, 논쟁하다", "arise": "발생하다",
        "arrange": "배열하다, 준비하다", "arrest": "체포하다", "arrive": "도착하다", "artificial": "인공적인",
        "aspect": "측면, 양상", "aspire": "열망하다", "assault": "공격, 폭행", "assemble": "조립하다, 모으다",
        "assert": "주장하다", "assess": "평가하다", "assign": "배정하다", "assist": "돕다",
        "associate": "연상하다, 관련시키다", "assume": "가정하다, 맡다", "assure": "확신시키다", "atmosphere": "대기, 분위기",
        "attach": "부착하다", "attack": "공격하다", "attain": "달성하다", "attempt": "시도하다",

        # [101-200] 빈출 어휘 세트
        "attitude": "태도, 사고방식", "attract": "끌어들이다", "attribute": "속성, ~의 탓으로 돌리다", "audience": "청중, 관객",
        "author": "작가, 저자", "authority": "권위, 당국", "available": "이용 가능한", "average": "평균의",
        "avoid": "피하다", "award": "상, 수여하다", "aware": "알고 있는", "awful": "끔찍한",
        "awkward": "어색한, 서투른", "balance": "균형, 잔고", "ban": "금지하다", "barely": "간신히, 거의 ~않다",
        "barrier": "장벽, 장애물", "base": "기초, 토대", "behalf": "이익, 지지", "behave": "행동하다",
        "belief": "믿음, 신념", "belong": "~에 속하다", "benefit": "이익, 혜택", "betray": "배신하다",
        "bewildered": "당혹해 하는", "bias": "편견, 선입견", "bid": "입찰하다, 시도하다", "bind": "묶다, 결속시키다",
        "biography": "전기, 일대기", "blame": "비난하다", "blend": "섞다, 혼합하다", "bless": "축복하다",
        "block": "차단하다, 구역", "bloom": "꽃이 피다", "boast": "자랑하다", "bond": "유대, 결속",
        "border": "국경, 경계", "boredom": "지루함", "borrow": "빌리다", "bother": "괴롭히다",
        "boundary": "경계(선)", "brake": "브레이크, 제동", "branch": "나뭇가지, 지점", "brave": "용감한",
        "breakthrough": "돌파구, 비약적 발전", "breathe": "숨을 쉬다", "brief": "잠시의, 간결한", "brilliant": "훌륭한, 빛나는",
        "broad": "넓은, 광범위한", "broadcast": "방송하다", "browse": "둘러보다", "brutal": "잔혹한",
        "budget": "예산", "burden": "짐, 부담", "burst": "터지다, 폭발하다", "bury": "묻다, 매장하다",
        "calculate": "계산하다", "campaign": "캠페인, 운동", "candidate": "후보자", "capable": "~할 수 있는",
        "capacity": "용량, 능력", "capital": "자본, 수도, 대문자", "capture": "포획하다", "career": "경력, 직업",
        "careful": "조심스러운", "category": "범주, 카테고리", "cause": "원인, 일으키다", "caution": "주의, 경고",
        "cease": "중단하다", "celebrate": "축하하다", "cell": "세포, 칸", "century": "세기, 100년",
        "certain": "확실한, 특정한", "certificate": "증명서, 자격증", "challenge": "도전, 난제", "chamber": "방, 회의실",
        "chaos": "혼란, 무질서", "character": "성격, 특징, 등장인물", "charge": "요금, 책임, 충전", "charity": "자선(단체)",
        "charm": "매력", "chase": "추격하다", "chat": "수다를 떨다", "cheap": "저렴한",
        "check": "확인하다, 억제", "cheerful": "쾌활한", "cherish": "소중히 여기다", "chew": "씹다",
        "chief": "주요한, 우두머리", "chill": "냉기, 한기", "choice": "선택", "choir": "합창단",
        "chronic": "만성적인", "circumstance": "상황, 환경", "cite": "인용하다", "citizen": "시민",
        "civil": "시민의, 민간의", "claim": "주장하다, 요구하다", "clarify": "명확하게 하다", "classic": "전형적인, 고전의",

        # [201-300] C-D 그룹
        "classify": "분류하다", "client": "의뢰인, 고객", "clue": "단서, 실마리", "clumsy": "어색한, 서투른",
        "cluster": "무리, 송이", "coach": "코치, 지도하다", "coalition": "연합, 합동", "coarse": "거친, 조잡한",
        "code": "암호, 규범", "cognitive": "인식의, 인지적인", "coherent": "일관성 있는", "coincidence": "우연의 일치",
        "collaborate": "협력하다", "collapse": "무너지다, 붕괴하다", "colleague": "동료", "collect": "수집하다",
        "combine": "결합하다", "comfort": "편안함, 위로하다", "command": "명령하다, 지휘하다", "commemorate": "기념하다",
        "comment": "논평, 언급하다", "commerce": "상업, 무역", "commit": "범하다, 약속하다, 전념하다", "committee": "위원회",
        "commodity": "상품, 물자", "communicate": "의사소통하다", "community": "지역사회, 공동체", "companion": "동료, 동반자",
        "compare": "비교하다", "compassion": "동정심, 연민", "compatible": "호환이 되는, 양립 가능", "compensate": "보상하다",
        "compete": "경쟁하다", "competent": "유능한, 역량 있는", "complain": "불평하다", "complement": "보안하다, 보충물",
        "complete": "완성하다, 완전한", "complex": "복잡한, 단지", "compliment": "칭찬", "comply": "따르다, 준수하다",
        "component": "구성 요소", "compose": "구성하다, 작곡하다", "compound": "혼합물, 합성의", "comprehend": "이해하다",
        "comprise": "구성되다, 포함하다", "compromise": "타협하다", "compulsory": "의무적인, 강제적인", "conceal": "숨기다, 은닉하다",
        "concede": "인정하다, 양보하다", "conceive": "상상하다, 임신하다", "concentrate": "집중하다", "concept": "개념",
        "concern": "우려, 관심사", "conclude": "결론을 내리다", "concrete": "구체적인, 콘크리트", "condemn": "비난하다, 선고하다",
        "condition": "상태, 조건", "conduct": "수행하다, 실시하다", "confer": "상의하다, 수여하다", "confess": "자백하다, 고백하다",
        "confidence": "신뢰, 자신감", "confine": "국한시키다, 가두다", "confirm": "확인하다, 확정하다", "conflict": "갈등, 충돌",
        "conform": "따르다, 순응하다", "confront": "직면하다, 맞서다", "confuse": "혼란시키다", "congratulate": "축하하다",
        "congress": "회의, 국회", "connect": "연결하다", "conscience": "양심", "conscious": "의식하는, 자각하는",
        "consecutive": "연속적인", "consent": "동의하다", "consequence": "결과, 중요성", "conserve": "보존하다, 보호하다",
        "consider": "고려하다", "consist": "구성되다", "consistent": "일관된", "constant": "끊임없는, 불변의",
        "constitute": "구성하다, 제정하다", "constrain": "강요하다, 제약하다", "construct": "건설하다, 구성하다", "consult": "상담하다, 참고하다",
        "consume": "소비하다", "contact": "접촉, 연락하다", "contain": "포함하다, 억제하다", "contemporary": "현대의, 동시대의",
        "contempt": "경멸, 모욕", "contend": "다투다, 주장하다", "content": "내용물, 만족하는", "contest": "대회, 경쟁",
        "context": "문맥, 상황", "continent": "대륙", "continue": "계속하다", "contract": "계약, 수축하다",
        "contradict": "반박하다, 모순되다", "contrast": "대조", "contribute": "기여하다, 원인이 되다", "control": "통제하다",
        "controversial": "논란의 여지가 있는",

        # [301-400] C-D 추가 그룹
        "convenience": "편의, 편리", "convert": "전환하다, 바꾸다", "convey": "전달하다, 운반하다", "convince": "확신시키다, 설득하다",
        "cooperate": "협력하다", "coordinate": "조정하다, 통합하다", "cope": "대처하다, 맞서다", "core": "핵심, 핵심의",
        "corporate": "기업의, 법인의", "correspond": "일치하다", "corrupt": "부패한, 타락시키다", "costly": "비싼, 대가가 큰",
        "council": "의회, 자문위원회", "counsel": "상담, 조언하다", "counter": "계산대, 반대하다", "counterpart": "대응 관계에 있는 사람/사물",
        "countless": "무수한", "courage": "용기", "courtesy": "예의, 공손", "coward": "겁쟁이",
        "craft": "공예, 기술, 선박", "crash": "충돌하다, 추락하다", "create": "창조하다", "creature": "생물, 피조물",
        "credible": "믿을 수 있는", "credit": "신용, 업적, 학점", "creed": "신조, 신념", "crew": "승무원, 팀",
        "crime": "범죄", "crisis": "위기", "critic": "비평가", "critical": "비판적인, 결정적인",
        "criticize": "비난하다, 비평하다", "crop": "농작물, 수확물", "crucial": "중요한, 결정적인", "cruel": "잔혹한",
        "crush": "으깨다, 진압하다", "cultivate": "경작하다, 기르다", "culture": "문화", "cure": "치료하다",
        "curiosity": "호기심", "current": "현재의, 흐름", "curriculum": "교과 과정", "custom": "관습, 습관",
        "cycle": "순환, 주기", "damage": "손상, 피해", "dash": "돌진하다", "deadline": "마감 기한",
        "debate": "토론, 논쟁", "debt": "빚, 채무", "decade": "10년", "decay": "부패하다, 쇠퇴하다",
        "deceive": "속이다", "decent": "괜찮은, 예의 바른", "declare": "선언하다", "decline": "거절하다, 감소하다",
        "decorate": "장식하다", "decrease": "감소하다", "dedicate": "헌신하다, 바치다", "deduce": "추론하다",
        "defeat": "패배시키다", "defect": "결점, 결함", "defend": "방어하다", "deficiency": "결핍, 부족",
        "define": "정의하다", "definite": "확실한, 명확한", "deform": "변형시키다", "defy": "반대하다, 거역하다",
        "degree": "도, 정도, 학위", "delay": "연기하다, 지연", "delegate": "대표자, 위임하다", "deliberate": "의도적인, 신중한",
        "delicate": "섬세한, 미묘한", "delight": "기쁨", "deliver": "배달하다, 연설하다", "demand": "요구하다, 수요",
        "democracy": "민주주의", "demolish": "파괴하다, 허물다", "demonstrate": "입증하다, 시위하다", "denial": "부인, 거절",
        "dense": "밀집한, 빽빽한", "depart": "출발하다", "depend": "의존하다", "depict": "묘사하다",
        "deposit": "예금하다, 보증금", "depress": "우울하게 하다, 침체시키다", "deprive": "빼앗다, 박탈하다", "derive": "이끌어내다, 유래하다",
        "descend": "내려가다, 하강하다", "describe": "묘사하다, 설명하다", "deserve": "~할 가치가 있다", "design": "설계하다, 디자인",
        "designate": "지정하다, 지명하다", "desperate": "필사적인, 절망적인", "despise": "경멸하다", "despite": "~에도 불구하고",
        "destination": "목적지", "destiny": "운명", "destroy": "파괴하다", "detach": "떼다, 분리하다",
        "detail": "세부 사항", "detain": "구금하다, 지체시키다", "detect": "감지하다, 찾아내다", "deteriorate": "악화되다",
        "determine": "결정하다", "devastate": "황폐화시키다", "develop": "개발하다, 발달하다", "device": "장치, 기구",
        "devise": "고안하다", "devote": "바치다, 전념하다", "diagnose": "진단하다", "dialect": "방언, 사투리",
        "dialogue": "대화", "dictate": "받아쓰게 하다, 지시하다", "differ": "다르다",

        # [401-500] D-E 그룹
        "differentiate": "구별하다, 차별화하다", "diffuse": "퍼뜨리다, 확산시키다", "digest": "소화하다, 요약하다", "dignity": "존엄, 품위",
        "diligent": "부지런한", "diminish": "줄어들다, 감소하다", "dip": "살짝 담그다", "diplomacy": "외교",
        "direct": "직접적인, 지휘하다", "disaster": "재난, 참사", "discard": "버리다, 폐기하다", "discipline": "훈육, 규율, 학문",
        "disclose": "폭로하다, 드러내다", "discount": "할인하다", "discourage": "낙담시키다, 방해하다", "discourse": "담론, 강연",
        "discover": "발견하다", "discriminate": "차별하다, 구별하다", "disguise": "변장하다, 위장", "dismiss": "해고하다, 묵살하다",
        "disorder": "무질서, 장애", "display": "전시하다, 보여주다", "dispose": "배치하다, 처분하다", "dispute": "분쟁, 논쟁하다",
        "disregard": "무시하다", "disrupt": "방해하다, 중단시키다", "distant": "먼, 거리를 두는", "distinct": "별개의, 뚜렷한",
        "distinguish": "구별하다", "distort": "왜곡하다", "distract": "주의를 돌리다", "distribute": "배포하다, 유통하다",
        "district": "지역, 구역", "disturb": "방해하다", "diverse": "다양한", "divide": "나누다",
        "divine": "신의, 신성한", "divorce": "이혼", "document": "문서, 기록하다", "domestic": "국내의, 가정의",
        "dominant": "지배적인, 우세한", "donate": "기부하다", "doom": "운명, 비운", "dormant": "휴면기의, 활동 중단된",
        "dose": "복용량", "doubt": "의심하다", "drain": "배수하다, 소모시키다", "dramatic": "극적인",
        "dread": "두려워하다", "drift": "표류하다, 이동하다", "drill": "훈련, 드릴, 구멍 뚫기", "drought": "가뭄",
        "drown": "익사하다", "duplicate": "복사하다, 이중의", "durable": "내구성이 있는, 오래가는", "duration": "지속 시간",
        "duty": "의무, 세금", "dwell": "살다, 거주하다", "dye": "염료, 염색하다", "dynamic": "역동적인",
        "eager": "간절히 바라는, 열심인", "earn": "벌다, 얻다", "earthquake": "지진", "echo": "메아리, 울림",
        "ecology": "생태학", "economy": "경제, 절약", "edge": "가장자리, 우위", "edit": "편집하다",
        "educate": "교육하다", "effect": "효과, 영향, 결과", "efficient": "효율적인", "effort": "노력",
        "elaborate": "정교한, 상세히 설명하다", "elastic": "탄력 있는, 유연한", "elderly": "나이 든, 어르신들", "elect": "선출하다",
        "elegant": "우아한", "element": "요소, 성분", "eliminate": "제거하다", "eloquent": "유창한, 설득력 있는",
        "embark": "착수하다, 승선하다", "embarrass": "당황하게 하다", "embassy": "대사관", "embody": "구현하다, 구체화하다",
        "embrace": "포용하다, 받아들이다", "emerge": "나타나다, 드러나다", "emergency": "비상사태", "emit": "내뿜다, 방출하다",
        "emotion": "감정", "emphasis": "강조", "empire": "제국", "empirical": "경험적인, 실증적인",
        "employ": "고용하다, 이용하다", "enable": "가능하게 하다", "encounter": "마주치다", "encourage": "격려하다",
        "endure": "견디다, 참다",

        # [501-600] E-F 그룹
        "energy": "에너지, 활기", "enforce": "집행하다, 강요하다", "engage": "참여하다, 고용하다", "enhance": "향상시키다, 높이다",
        "enlighten": "계몽하다, 깨우치게 하다", "enormous": "거대한, 엄청난", "enroll": "등록하다, 입학하다", "ensure": "보장하다, 확실히 하다",
        "enterprise": "기업, 사업", "entertain": "즐겁게 하다", "enthusiasm": "열정, 열광", "entire": "전체의",
        "entitle": "자격을 주다, 제목을 붙이다", "entity": "독립체, 본체", "entrance": "입구, 입장", "entrepreneur": "기업가, 사업가",
        "environment": "환경", "envy": "부러워하다, 질투", "episode": "사건, 에피소드", "equal": "같은, 평등한",
        "equip": "장비를 갖추다", "equivalent": "상당하는, 동등한 것", "erase": "지우다", "erect": "세우다, 똑바로 선",
        "erroneous": "잘못된", "error": "오류, 실수", "escape": "달아나다, 탈출", "escort": "호위하다, 동행하다",
        "essay": "수필, 과제물", "essence": "본질, 정수", "establish": "설립하다, 확립하다", "estate": "재산, 토지",
        "estimate": "추정하다, 견적", "eternal": "영원한", "ethics": "윤리, 도덕", "ethnic": "민족의, 인종의",
        "evacuate": "대피시키다", "evaluate": "평가하다", "evaporate": "증발하다", "event": "사건, 행사",
        "eventual": "최종적인", "evidence": "증거", "evident": "분명한, 명백한", "evil": "악, 사악한",
        "evolve": "진화하다, 발달하다", "exaggerate": "과장하다", "examine": "조사하다, 검토하다", "example": "예시",
        "exceed": "넘다, 초과하다", "excellent": "우수한", "except": "~을 제외하고", "excessive": "과도한",
        "exchange": "교환하다", "excite": "흥분시키다", "exclude": "제외하다", "exclusive": "독점적인, 배타적인",
        "excursion": "소풍, 유람", "excuse": "변명, 용서하다", "execute": "실행하다, 처형하다", "executive": "경영진, 행정부",
        "exemplify": "전형적인 예가 되다", "exempt": "면제된", "exercise": "운동, 연습, 행사하다", "exert": "발휘하다, 노력하다",
        "exhaust": "지치게 하다, 배기가스", "exhibit": "전시하다", "exile": "망명, 유배", "exist": "존재하다",
        "exit": "출구, 나가다", "exotic": "외래의, 이국적인", "expand": "확장하다", "expect": "기대하다, 예상하다",
        "expedition": "탐험, 원정", "expel": "추방하다, 제명하다", "expend": "소비하다, 쓰다", "expense": "비용, 지출",
        "experience": "경험", "experiment": "실험", "expert": "전문가", "expire": "만료되다",
        "explain": "설명하다", "explicit": "명백한, 노골적인", "explode": "폭발하다", "exploit": "이용하다, 착취하다",
        "explore": "탐험하다", "export": "수출하다", "expose": "노출시키다", "express": "표현하다, 급행의",
        "extend": "연장하다, 뻗다", "exterior": "외부의", "external": "외부의, 밖의", "extinct": "멸종된",
        "extinguish": "끄다, 끝내다", "extra": "추가의", "extract": "추출하다", "extraordinary": "비범한, 놀라운",
        "extreme": "극도로, 극심한", "fabric": "직물, 천, 구조", "fabulous": "기막히게 좋은", "facilitate": "용이하게 하다",
        "facility": "시설, 편의",

        # [601-700] F-G 그룹
        "factor": "요인, 요소", "faculty": "능력, 학부, 교수진", "fade": "서서히 사라지다, 시들다", "failure": "실패",
        "faint": "희미한, 기절하다", "fair": "공정한, 박람회", "faith": "믿음, 신념", "false": "거짓의, 틀린",
        "fame": "명성", "familiar": "익숙한, 친숙한", "famine": "기근, 굶주림", "famous": "유명한",
        "fancy": "화려한, 상상하다", "fantastic": "환상적인", "fare": "요금, 운임", "fascinate": "매혹하다",
        "fashion": "유행, 방식, 만들다", "fasten": "매다, 고정시키다", "fatal": "치명적인", "fate": "운명",
        "fatigue": "피로", "fault": "잘못, 결점", "favor": "호의, 찬성하다", "favorable": "호의적인, 유리한",
        "fear": "두려움", "feasible": "실행 가능한", "feat": "업적, 위업", "feature": "특징, 이목구비, 특집",
        "federal": "연방의", "fee": "수수료, 요금", "feeble": "약한, 가냘픈", "feed": "먹이를 주다",
        "feedback": "피드백, 반응", "fellow": "동료, 녀석", "female": "여성의", "fertile": "비옥한, 다산의",
        "festival": "축제", "fetch": "가지고 오다", "feudal": "봉건제의", "fiber": "섬유(질)",
        "fiction": "소설, 허구", "field": "들판, 분야", "fierce": "격렬한, 사나운", "figure": "수치, 인물, 모양, 판단",
        "filter": "여과기, 거르다", "final": "마지막의, 결승전", "finance": "재무, 금융, 자금 대기", "finding": "결과, 발견",
        "fine": "좋은, 가느다란, 벌금", "finish": "끝내다", "finite": "한정된, 유한한", "firm": "단단한, 확고한, 회사",
        "fist": "주먹", "fit": "적합한, 건강한", "fix": "고정시키다, 수리하다", "flame": "불꽃",
        "flap": "펄럭거리다", "flare": "확 타오르다", "flash": "번쩍임", "flat": "평평한, 단조로운",
        "flatter": "아부하다", "flavor": "맛, 풍미", "flaw": "결점, 흠", "flee": "달아나다, 도망치다",
        "fleet": "함대, 빠른", "flesh": "살, 육체", "flexible": "유연한, 융통성 있는", "flight": "비행",
        "float": "뜨다, 떠다니다", "flock": "떼, 무리", "flood": "홍수, 범람시키다", "flourish": "번창하다",
        "flow": "흐름, 흐르다", "fluctuate": "변동하다, 오르내리다", "fluent": "유창한", "fluid": "유체, 액체, 가변적",
        "flush": "붉어지다, 물 내리기", "flyer": "전단지", "focus": "집중하다", "fold": "접다",
        "folk": "사람들, 민속의", "follow": "따르다", "fond": "좋아하는", "forbid": "금지하다",
        "force": "힘, 강요하다", "forecast": "예보, 예측하다", "forehead": "이마", "foreign": "외국의",
        "foremost": "으뜸가는, 주요한", "foresee": "예견하다", "forest": "숲", "forever": "영원히",
        "forge": "구축하다, 위조하다", "forget": "잊다", "forgive": "용서하다", "formal": "공식적인, 격식",
        "format": "형식, 구성", "formation": "형성, 대형", "former": "이전의, 전자", "formidable": "가공할, 어마어마한",
        "formula": "공식, 방식",

        # [701-800] 빈출 혼합 세트 (G-H-I-L)
        "forth": "앞으로, 밖으로", "fortify": "강화하다", "fortunate": "운 좋은", "fortune": "운, 재산",
        "forward": "앞으로, 송신하다", "foster": "육성하다, 아이 기르기", "foundation": "토대, 기초, 재단", "fraction": "부분, 파편, 분수",
        "fragile": "깨지기 쉬운, 취약한", "fragment": "파편, 조각", "frame": "틀, 뼈대", "frank": "솔직한",
        "fraud": "사기, 속임수", "freedom": "자유", "freeze": "얼다, 결빙", "frequent": "빈번한",
        "fresh": "신선한", "friction": "마찰, 갈등", "frighten": "놀라게 하다", "frontier": "국경, 접경 지역",
        "frown": "눈살을 찌푸리다", "frugal": "절약하는, 소박한", "frustrate": "좌절시키다", "fuel": "연료, 에너지 주다",
        "fulfill": "이행하다, 완수하다", "function": "기능, 작동하다", "fund": "자금, 기금", "fundamental": "근본적인, 핵심적인",
        "funeral": "장례식", "furious": "몹시 화난", "furnish": "제공하다, 가구 비치", "furthermore": "게다가, 더욱이",
        "future": "미래", "gain": "얻다, 이익", "galaxy": "은하계", "gamble": "도박하다",
        "gap": "격차, 틈", "garbage": "쓰레기", "garment": "의복, 옷", "gather": "모으다, 수집하다",
        "gauge": "측정하다, 척도", "gear": "장비, 기어", "gene": "유전자", "general": "일반적인, 장군",
        "generate": "발생시키다", "generous": "관대한, 너그러운", "genius": "천재", "gentle": "부드러운, 온화한",
        "genuine": "진짜의, 진실한", "gesture": "몸짓, 제스처", "giant": "거대한", "gift": "선물, 타고난 재능",
        "glance": "흘긋 봄, 훑어보다", "glare": "노려보다, 눈부신 빛", "glass": "유리, 안경", "global": "지구촌의, 포괄적인",
        "glory": "영광", "glossary": "용어 사전", "glow": "빛나다, 타오르다", "goal": "목표",
        "goods": "상품, 제품", "govern": "다스리다, 통제하다", "grace": "우아함, 은총", "gradual": "점진적인",
        "graduate": "졸업하다", "grain": "곡물, 알갱이", "grand": "웅장한, 원대한", "grant": "승인하다, 보조금",
        "graphic": "생생한, 도표의", "grasp": "꽉 잡다, 이해하다", "grass": "풀, 잔디", "grateful": "감사하는",
        "gratitude": "고마움, 감사", "gravity": "중력, 중대함", "gray": "회색의", "greed": "탐욕",
        "greenhouse": "온실", "greet": "인사하다", "grief": "슬픔, 비탄", "grim": "엄격한, 암울한",
        "grin": "활짝 웃다", "grind": "갈다, 연마하다", "grip": "꽉 쥠, 파악하다", "grocery": "식료품",
        "gross": "총합의, 비속한", "ground": "지면, 근거", "group": "그룹, 집단", "grow": "성장하다",
        "guarantee": "보장하다, 품질 보증", "guard": "보초, 보호하다", "guess": "추측하다", "guest": "손님",
        "guide": "안내하다", "guilt": "죄책감, 유죄", "habit": "습관", "habitat": "서식지",
        "hall": "회관, 복도", "halt": "멈추다, 중단", "hammer": "망치", "handicap": "불리한 조건, 장애",
        "handle": "다루다, 처리하다, 손잡이",
        "handy": "유용한, 가까이 있는",
        "harbor": "항구, 거처, (생각 등을) 품다",
        "hardship": "고난, 어려움",
        "harm": "해치다, 손해",
        "harmony": "조화, 일치",
        "harsh": "가혹한, 거친",
        "harvest": "수확하다, 추수",
        "haste": "서두름, 성급함",
        "hatred": "증오, 미움",
        "hazard": "위험, 모험",
        "headquarters": "본부, 본사",
        "heal": "치료하다, 고치다",
        "heap": "더미, 쌓아 올리다",
        "heart": "심장, 핵심, 마음",
        "heaven": "천국, 하늘",
        "heavy": "무거운, 심한",
        "height": "높이, 절정",
        "heir": "상속인, 후계자",
        "helmet": "헬멧, 안전모",
        "hence": "따라서, 그러므로",
        "herald": "알리다, 예고하다",
        "herd": "짐승의 떼, 무리",
        "heritage": "유산, 전통",
        "hesitate": "망설이다, 주저하다",
        "hide": "숨기다, 짐승의 가죽",
        "hierarchy": "계급, 위계",
        "highlight": "강조하다, 핵심",
        "highway": "고속도로",
        "hijack": "납치하다, 강탈하다",
        "hinder": "방해하다, 저지하다",
        "hint": "암시, 힌트",
        "hire": "고용하다",
        "historic": "역사적으로 중요한",
        "hollow": "속이 빈, 움푹한 곳",
        "holy": "신성한",
        "homage": "존경, 경의",
        "honest": "정직한",
        "honor": "명예, 존경하다",
        "horizon": "지평선, 수평선, 시야",
        "horizontal": "가로의, 수평의",
        "hormone": "호르몬",
        "horrible": "끔찍한",
        "horror": "공포",
        "hospitable": "환대하는, 쾌적한",
        "hospital": "병원",
        "host": "주인, 주최하다",
        "hostage": "인질",
        "hostile": "적대적인",
        "household": "가족, 가구",
        "huge": "거대한",
        "humane": "인도적인, 자비로운",
        "humble": "겸손한, 비천한",
        "humid": "습한",
        "humiliate": "굴욕감을 주다",
        "humor": "유머, 해학",
        "hunt": "사냥하다",
        "hurdle": "장애물, 허들",
        "hurl": "내던지다",
        "hurricane": "허리케인",
        "hurry": "서두르다",
        "hybrid": "혼성, 하이브리드",
        "hypothesis": "가설",
        "ideal": "이상적인",
        "identical": "동일한",
        "identify": "확인하다, 동일시하다",
        "identity": "정체성, 신원",
        "ideology": "이데올로기, 관념",
        "idiom": "관용구, 숙어",
        "idle": "게으른, 가동되지 않는",
        "ignore": "무시하다",
        "ill": "아픈, 나쁜",
        "illegal": "불법의",
        "illiterate": "문맹의",
        "illuminate": "비추다, 계몽하다",
        "illusion": "환상, 착각",
        "illustrate": "삽화를 넣다, 설명하다",
        "image": "이미지, 상",
        "imaginary": "상상의, 가상의",
        "imitate": "모방하다",
        "immediate": "즉각적인",
        "immense": "거대한, 엄청난",
        "immerse": "담그다, 몰두시키다",
        "immigrant": "이민자",
        "immune": "면역의, 면제된",
        "impact": "영향, 충격",
        "impaired": "손상된, 장애가 있는",
        "impartial": "공정한",
        "impatient": "조급한, 참을성 없는",
        "imperative": "필수적인, 명령",
        "implement": "도구, 실행하다",
        "implication": "암시, 영향",
        "imply": "함축하다, 암시하다",
        "import": "수입하다",
        "impose": "부과하다, 강요하다",
        "impossible": "불가능한",
        "impress": "인상을 주다, 감동시키다",
        "imprison": "투옥하다",
        "improve": "개선하다",
        "impulse": "충동, 자극",
        "inadequate": "불충분한, 부적절한",
        "incentive": "동기, 자극, 장려책",
        "incident": "사건, 일어난 일",
        "incline": "마음이 내키게 하다, 경사",
        "include": "포함하다",
        "income": "수입, 소득",
        "incorporate": "통합하다, 포함하다",
        "increase": "증가하다",
        "incredible": "믿기 힘든, 놀라운",
        "independ": "독립하다, 의존하지 않다",
        "index": "색인, 지표",
        "indicate": "나타내다, 가리키다",
        "indifference": "무관심",
        "indigenous": "지역 고유의, 토착의",
        "indignant": "분개한, 성난",
        "individual": "개인, 개개의",
        "induce": "유도하다, 유발하다",
        "indulge": "마음껏 하다, 탐닉하다",
        "industry": "산업, 근면",
        "inevitable": "피할 수 없는, 필연적인",
        "infant": "유아, 아기",
        "infect": "감염시키다",
        "infer": "추론하다",
        "inferior": "열등한, 하위의",
        "infinite": "무한한",
        "inflation": "팽창, 물가 상승",
        "influence": "영향을 미치다",
        "inform": "알리다, 통지하다",
        "informal": "비격식적인, 편안한",
        "ingredient": "재료, 성분",
        "inhabit": "거주하다, 살다",
        "inherent": "타고난, 내재된",
        "inherit": "상속받다, 물려받다",
        "inhibit": "억제하다, 저해하다",
        "initial": "처음의, 초기의",
        "initiate": "시작하다, 개시하다",
        "inject": "주입하다, 주사하다",
        "injure": "상처를 입히다",
        "innate": "타고난, 천성의",
        "innocent": "결백한, 순진한",
        "innovate": "혁신하다",
        "innumerable": "무수한",
        "input": "입력, 투입",
        "inquire": "묻다, 조사하다",
        "insane": "제정신이 아닌, 미친",
        "inscribe": "새기다, 쓰다",
        "insect": "곤충",
        "insert": "삽입하다",
        "insight": "통찰력",
        "insist": "주장하다, 고집하다",
        "inspect": "검사하다, 점검하다",
        "inspire": "영감을 주다, 고취하다",
        "install": "설치하다",
        "instance": "사례, 경우",
        "instant": "즉각적인, 순간",
        "instinct": "본능",
        "institute": "기관, 협회, 도입하다",
        "instruct": "가르치다, 지시하다",
        "instrument": "기구, 악기, 도구",
        "insulate": "절연하다, 격리하다",
        "insult": "모욕하다",
        "insurance": "보험",
        "intact": "온전한, 손상되지 않은",
        "intake": "섭취(량)",
        "integrate": "통합하다",
        "intellectual": "지적인, 지식인",
        "intelligence": "지능, 정보",
        "intend": "의도하다",
        "intense": "강렬한, 치열한",
        "interact": "상호작용하다",
        "intercept": "가로채다",
        "interfere": "간섭하다, 방해하다",
        "intermediate": "중급의, 중간의",
        "internal": "내부의",
        "interpret": "해석하다, 통역하다",
        "interrupt": "중단시키다, 방해하다",
        "interval": "간격, 틈",
        "intervene": "개입하다, 끼어들다",
        "intimate": "친밀한",
        "intimidate": "위협하다, 겁주다",
        "intricate": "복잡한",
        "intrigue": "흥미를 끌다, 음모",
        "introduce": "소개하다, 도입하다",
        "intrude": "침범하다, 방해하다",
        "intuition": "직관(력)",
        "invade": "침략하다",
        "invalid": "무효한, 병약한",
        "invaluable": "매우 귀중한",
        "invariably": "변함없이, 예외 없이",
        "invent": "발명하다",
        "inventory": "재고 목록",
        "inverse": "반대의, 역의",
        "invest": "투자하다",
        "investigate": "조사하다, 수사하다",
        "invisible": "보이지 않는",
        "invite": "초대하다",
        "invoke": "기원하다, 호소하다",
        "involve": "포함하다, 관련시키다",
        "irony": "반어법, 아이러니",
        "irrelevant": "무관한, 상관없는",
        "isolate": "고립시키다",
        "issue": "문제, 발행물, 발행하다",
        "item": "항목, 품목",
        "jail": "교도소, 감옥",
        "jealous": "질투하는",
        "jeopardize": "위험에 빠뜨리다",
        "jerk": "갑자기 움직이다, 얼간이",
        "joint": "공동의, 관절",
        "journal": "잡지, 일기, 신문",
        "journey": "여정, 여행",
        "judge": "판단하다, 재판관",
        "judicial": "사법의, 재판의",
        "junction": "교차로, 연결 지점",
        "jungle": "밀림, 정글",
        "junior": "하급의, 후배의",
        "jury": "배심원단",
        "justice": "정의, 사법",
        "justify": "정당화하다",
        "keen": "열망하는, 예리한",
        "kidnap": "유괴하다",
        "kind": "친절한, 종류",
        "kinship": "친족 관계, 유사",
        "knight": "기사",
        "knit": "짜다, 뜨개질하다",
        "knot": "매듭",
        "know": "알다",
        "knowledge": "지식",
        "label": "라벨을 붙이다, 상표",
        "labor": "노동, 수고",
        "laboratory": "실험실",
        "lack": "부족, ~이 없다",
        "ladder": "사다리",
        "lag": "뒤처지다, 지연",
        "landscape": "풍경, 경치",
        "lane": "차선, 통로",
        "language": "언어",
        "lantern": "랜턴, 등불",
        "lap": "무릎, 한 바퀴",
        "largely": "주로, 대체로",
        "laser": "레이저",
        "last": "마지막의, 지속되다",
        "latent": "잠재적인",
        "lateral": "측면의",
        "latter": "후자의, 뒷부분의",
        "laugh": "웃다",
        "launch": "출시하다, 발사하다",
        "lavish": "풍성한, 사치스러운",
        "law": "법",
        "lawyer": "변호사",
        "lay": "놓다, 낳다",
        "layer": "층, 겹",
        "lead": "이끌다, 납",
        "leaf": "잎사귀",
        "leak": "새다, 누출",
        "lean": "기울이다, 마른",
        "leap": "도약하다, 뛰다",
        "learn": "배우다",
        "lease": "임대하다",
        "leather": "가죽",
        "leave": "떠나다, 남겨두다",
        "lecture": "강의",
        "legal": "법적인, 합법의",
        "legend": "전설",
        "legislate": "법률을 제정하다",
        "legitimate": "정당한, 타당한",
        "leisure": "여가, 한가함",
        "lend": "빌려주다",
        "length": "길이",
        "lens": "렌즈",
        "lessen": "줄이다",
        "lesson": "교훈, 수업",
        "lethal": "치명적인",
        "level": "수준, 평평한",
        "liable": "~하기 쉬운, 책임이 있는",
        "liberal": "자유주의의, 관대한",
        "liberate": "해방시키다",
        "liberty": "자유",
        "library": "도서관",
        "license": "면허, 자격",
        "lick": "핥다",
        "lie": "거짓말하다, 눕다",
        "life": "인생, 생명",
        "lift": "들어 올리다",
        "light": "빛, 가벼운",
        "likely": "~할 것 같은",
        "likewise": "마찬가지로",
        "limit": "한계, 제한하다",
        "line": "선, 줄",
        "linger": "남아 있다, 서성대다",
        "linguistic": "언어의",
        "link": "연결하다",
        "liquid": "액체",
        "list": "목록",
        "listen": "듣다",
        "literacy": "읽고 쓰는 능력",
        "literal": "글자 그대로의",
        "literary": "문학의",
        "literature": "문학",
        "litter": "쓰레기, 어지르다",
        "little": "작은, 거의 없는",
        "live": "살다, 생방송의",
        "abandonment": "유기, 포기",
        "abnormal": "비정상적인",
        "abolish": "폐지하다",
        "abrupt": "갑작스러운",
        "absence": "결석, 부재",
        "absolute": "절대적인",
        "abundance": "풍부함",
        "abuse": "남용, 학대",
        "accelerate": "가속화하다",
        "accessible": "접근 가능한",
        "accommodation": "숙박 시설",
        "accompanying": "동반하는",
        "accomplish": "완수하다",
        "accordingly": "따라서",
        "accumulation": "축적",
        "accustomed": "익숙한",
        "acquaintance": "지인, 아는 사람",
        "acquisition": "습득, 획득",
        "activate": "활성화하다",
        "acute": "격심한, 예리한",
        "adhere": "고수하다, 들러붙다",
        "adjacent": "인접한",
        "adolescence": "청소년기",
        "adorn": "장식하다",
        "advent": "출현, 도래",
        "adverse": "부정적인, 불리한",
        "aesthetic": "미적인, 심미적인",
        "affection": "애정",
        "affiliate": "제휴하다, 계열사",
        "affirm": "단언하다, 확인하다",
        "afflict": "괴롭히다",
        "affluence": "풍요, 부유함",
        "aftermath": "여파, 결과",
        "aggravate": "악화시키다",
        "aggregate": "합계, 집합하다",
        "agony": "고통",
        "agreeable": "쾌적한, 동의할 수 있는",
        "agriculture": "농업",
        "alienate": "멀어지게 하다, 소외시키다",
        "allegation": "주장, 혐의",
        "alleviate": "완화하다",
        "alliance": "동맹",
        "allocation": "할당",
        "allowance": "용돈, 허용량",
        "alteration": "변경, 개조",
        "ambiguous": "모호한",
        "ambivalent": "반대 감정이 병존하는",
        "amend": "개정하다",
        "ample": "충분한",
        "amplify": "증폭시키다",
        "analogy": "비유, 유추",
        "anonymous": "익명의",
        "apparatus": "장치, 기구",
        "applaud": "박수치다",
        "appliance": "가전제품",
        "applicable": "적용 가능한",
        "appraisal": "평가",
        "apprehend": "체포하다, 파악하다",
        "archive": "기록 보관소",
        "ardent": "열렬한",
        "arrogant": "오만한",
        "articulate": "또박또박 말하다, 명확한",
        "ascertain": "확인하다",
        "ascribe": "~의 탓으로 돌리다",
        "assure": "장담하다, 확언하다",
        "astonish": "깜짝 놀라게 하다",
        "asymmetry": "비대칭",
        "attachment": "부착, 애착",
        "attain": "달성하다",
        "attendance": "출석",
        "attentive": "주의 깊은",
        "attest": "증명하다",
        "attire": "의상, 복장",
        "auction": "경매",
        "audible": "들리는",
        "augment": "늘리다, 증가시키다",
        "authentic": "진본의, 진짜인",
        "authoritative": "권위 있는",
        "authorize": "권한을 부여하다",
        "autonomy": "자율성, 자치",
        "availability": "가용성",
        "avenge": "복수하다",
        "aviation": "항공",
        "awkwardness": "어색함",
        "axis": "축",
        "bachelor": "학사, 미혼남",
        "backfire": "역효과를 내다",
        "backlash": "반발",
        "baffle": "당황하게 하다",
        "baggage": "수하물, 짐",
        "banish": "추방하다",
        "bankruptcy": "파산",
        "barren": "척박한, 불모의",
        "baseless": "근거 없는",
        "bashful": "수줍음을 타는",
        "beaming": "기쁨에 찬",
        "behold": "바라보다",
        "belated": "늦은, 뒤늦은",
        "benchmark": "기준(점)",
        "beneficial": "유익한",
        "benevolent": "자비로운",
        "betrayal": "배신, 배반",
        "bewilder": "당황하게 하다",
        "biennial": "2년마다의",
        "blast": "폭발, 돌풍",
        "blatant": "노골적인, 뻔뻔한",
        "bleak": "암울한, 절망적인",
        "blessing": "축복, 승인",
        "blunder": "실수, 터무니없는 실수",
        "blunt": "무딘, 직설적인",
        "blur": "흐릿하게 하다",
        "bondage": "속박, 굴레",
        "boost": "증대시키다, 격려",
        "brace": "대비하다, 버팀대",
        "breach": "위반, 파괴",
        "brisk": "활발한, 상쾌한",
        "brittle": "부서지기 쉬운",
        "capability": "능력, 역량",
        "casualty": "사상자, 피해자",
        "catastrophe": "대참사, 재앙",
        "cater": "요구를 들어주다, 음식을 공급하다",
        "cautionary": "권고의, 경고적인",
        "celebrated": "유명한",
        "censorship": "검열",
        "census": "인구 조사",
        "centered": "중심에 있는",
        "certainty": "확실성",
        "certification": "증명, 인증",
        "challenge": "도전, 이의를 제기하다",
        "chaos": "혼란, 무질서",
        "characteristic": "특징, 전형적인",
        "charitable": "자비로운, 자선의",
        "chatter": "수다를 떨다",
        "cherish": "소중히 여기다",
        "circular": "원형의, 순환하는",
        "circulate": "순환하다, 유포하다",
        "civilization": "문명",
        "clarification": "설명, 해명",
        "clarity": "명료함, 맑음",
        "clash": "충돌하다",
        "cleave": "쪼개다, 고수하다",
        "clench": "꽉 쥐다",
        "cling": "매달리다, 고수하다",
        "clue": "실마리, 단서",
        "clutter": "어지르다",
        "coincide": "일치하다, 동시에 일어나다",
        "collaboration": "협력, 공동 작업",
        "collective": "집단적인, 공동의",
        "collision": "충돌",
        "combat": "전투, 싸우다",
        "commence": "시작하다",
        "commend": "칭찬하다",
        "commentary": "해설, 논평",
        "commitment": "헌신, 약속",
        "communal": "공동의, 지역 사회의",
        "commute": "통근하다",
        "compact": "조밀한, 소형의",
        "comparable": "비교할 만한",
        "comparative": "비교의, 상대적인",
        "compassion": "동정, 연민",
        "compel": "강요하다",
        "compensate": "보상하다",
        "competence": "능력, 유능",
        "competitive": "경쟁적인",
        "compile": "편집하다, 수집하다",
        "complacency": "자기만족, 안주",
        "complementary": "상호 보충적인",
        "complexity": "복잡성",
        "compliance": "준수, 따름",
        "complication": "복잡한 문제, 합병증",
        "compliment": "칭찬, 경의",
        "component": "구성 요소",
        "composed": "침착한, 구성된",
        "composition": "구성, 작문",
        "comprehend": "이해하다",
        "comprehensive": "포괄적인",
        "compress": "압축하다",
        "compromise": "타협하다",
        "compulsory": "강제적인, 의무적인",
        "conceal": "숨기다",
        "concede": "인정하다, 양보하다",
        "conceive": "상상하다, 임신하다",
        "concentration": "집중, 농도",
        "conception": "개념, 구상",
        "concession": "양보, 허가",
        "concise": "간결한",
        "conclude": "결론짓다",
        "conclusive": "결정적인, 확실한",
        "concord": "일치, 화합",
        "concrete": "구체적인",
        "condemn": "비난하다",
        "condense": "농축하다, 요약하다",
        "condone": "용납하다, 눈감아주다",
        "conduct": "수행하다, 행동",
        "conference": "회의",
        "confide": "털어놓다",
        "confidence": "신뢰, 자신감",
        "confidential": "비밀의",
        "confine": "국한하다, 가두다",
        "confirm": "확인하다",
        "confiscate": "압수하다",
        "conflict": "갈등, 충돌",
        "conform": "순응하다, 일치하다",
        "confront": "직면하다",
        "confuse": "혼란시키다",
        "congestion": "혼잡",
        "congratulate": "축하하다",
        "conjunction": "결합, 접속사",
        "conquer": "정복하다",
        "conscience": "양심",
        "conscientious": "양심적인, 성실한",
        "conscious": "의식하는",
        "consecutive": "연속적인",
        "consensus": "합의, 일치",
        "consent": "동의하다",
        "consequence": "결과, 중요성",
        "consequent": "결과로서 일어나는",
        "conservation": "보존",
        "conservative": "보수적인",
        "considerable": "상당한",
        "considerate": "사려 깊은",
        "consist": "구성되다",
        "consistency": "일관성",
        "console": "위로하다",
        "conspicuous": "눈에 띄는",
        "conspiracy": "음모",
        "constant": "끊임없는",
        "constitute": "구성하다",
        "constitution": "헌법, 체질",
        "constrain": "제약하다, 강요하다",
        "constructive": "건설적인",
        "consult": "상담하다",
        "consume": "소비하다",
        "contaminate": "오염시키다",
        "contemplate": "심사숙고하다",
        "contemporary": "현대의, 동시대의",
        "contempt": "경멸",
        "contend": "주장하다, 다투다",
        "content": "내용물, 만족하는",
        "contentment": "만족",
        "contest": "대회, 논쟁하다",
        "context": "문맥, 상황",
        "continual": "반복되는, 끊임없는",
        "continuity": "연속성",
        "contradict": "모순되다, 반박하다",
        "contrary": "반대의",
        "contrast": "대조",
        "contribute": "기여하다",
        "controversial": "논란의 여지가 있는",
        "convenience": "편의",
        "convention": "관습, 집회",
        "converge": "모여들다",
        "conversely": "반대로",
        "convert": "전환하다",
        "convey": "전달하다",
        "convict": "유죄를 선고하다",
        "conviction": "신념, 유죄 판결",
        "convince": "확신시키다",
        "cooperate": "협력하다",
        "coordinate": "조정하다",
        "cope": "대처하다",
        "cordial": "진심 어린, 다정한",
        "corporate": "기업의",
        "correlate": "상관관계가 있다",
        "correspond": "일치하다, 서신을 주고받다",
        "corrupt": "부패한",
        "costly": "비싼",
        "council": "의회",
        "counsel": "조언, 상담",
        "counter": "반대하다, 계산대",
        "counterpart": "상대역, 대응 관계에 있는 사람",
        "countless": "무수한",
        "courageous": "용감한",
        "courteous": "예의 바른",
        "coverage": "보도, 범위",
        "cowardice": "겁, 비겁",
        "craftsmanship": "손재주, 장인 정신",
        "cranky": "짜증을 잘 내는",
        "crave": "갈망하다",
        "credibility": "신뢰성",
        "credible": "믿을 수 있는",
        "critical": "비판적인, 결정적인",
        "criticize": "비난하다",
        "crucial": "중요한",
        "crude": "가공하지 않은, 상스러운",
        "cruise": "순항하다",
        "crumble": "무너지다, 바스러지다",
        "culminate": "막을 내리다, 정점에 달하다",
        "culpable": "과실이 있는, 비난받을 만한",
        "cultivate": "경작하다, 양성하다",
        "cumulative": "누적되는",
        "curiosity": "호기심",
        "currency": "통화, 유통",
        "curriculum": "교육 과정",
        "curtail": "축소하다, 삭감하다",
        "customary": "관습적인",
        "cynical": "냉소적인",
        "dangle": "매달리다",
        "daring": "대담한",
        # [1401-1500] P-Q 그룹: 정책, 심리, 과학 관련
        "parallel": "평행한, 유사한", "paralyze": "마비시키다", "paramount": "최고의, 주요한", "parasite": "기생 생물",
        "pardon": "용서하다, 사면", "parliament": "의회, 국회", "partial": "부분적인, 편파적인", "participate": "참여하다",
        "particle": "입자, 아주 작은 조각", "particular": "특정한, 까다로운", "passage": "통로, 구절", "passenger": "승객",
        "passion": "열정", "passive": "수동적인", "pastime": "취미, 오락", "pasture": "목초지",
        "paternal": "아버지의, 부계의", "patience": "인내", "patriot": "애국자", "patron": "후원자, 단골",
        "pause": "중단하다", "pave": "길을 포장하다", "peak": "정점, 절정", "peculiar": "독특한, 이상한",
        "pedestrian": "보행자", "peer": "동료, 응시하다", "penalty": "처벌, 벌금", "penetrate": "관통하다, 침투하다",
        "perceive": "인지하다, 이해하다", "percentage": "백분율", "perfection": "완벽", "perform": "수행하다, 공연하다",
        "perfume": "향수", "peril": "위험", "period": "기간, 시대", "perish": "소멸하다, 죽다",
        "permanent": "영구적인", "permission": "허가", "perpetual": "끊임없는", "perplex": "당혹하게 하다",
        "persevere": "인내하다, 굴하지 않다", "persist": "고집하다, 지속되다", "perspective": "관점, 원근법", "persuade": "설득하다",
        "pertain": "속하다, 관련 있다", "pessimism": "비관주의", "pesticide": "살충제", "petition": "청원, 탄원",
        "phenomenon": "현상", "philosophy": "철학", "phrase": "구절, 관용구", "physical": "신체적인, 물리적인",
        "physician": "내과 의사", "physics": "물리학", "physiology": "생리학", "pierce": "뚫다, 관통하다",
        "pilgrim": "순례자", "pillar": "기둥", "pinnacle": "정점, 높이 솟은 봉우리", "pioneer": "개척자",
        "pious": "경건한", "pitfall": "함정, 숨겨진 위험", "pity": "동정, 연민", "plague": "전염병, 괴롭히다",
        "plain": "명백한, 평원", "planet": "행성", "plantation": "농장", "plausible": "그럴듯한",
        "plead": "간청하다, 변호하다", "pledge": "약속, 서약", "plenty": "풍부함", "plight": "곤경, 역경",
        "plot": "음모, 구성", "plunge": "급락하다, 뛰어들다", "poetry": "시", "policy": "정책, 방침",
        "polish": "닦다, 다듬다", "poll": "여론 조사, 투표", "pollute": "오염시키다", "ponder": "심사숙고하다",
        "portable": "휴대용의", "portion": "부분, 1인분", "portray": "묘사하다", "pose": "제기하다, 자세",
        "positive": "긍정적인", "possess": "소유하다", "postpone": "연기하다", "potential": "잠재적인",
        "poverty": "가난", "practical": "실용적인", "praise": "칭찬하다", "precede": "선행하다, 앞서다",
        "precious": "귀중한", "precise": "정확한", "precondition": "전제 조건", "precursor": "선구자",

        # [1501-1600] R 그룹: 관계, 반응, 연구 관련
        "radical": "근본적인, 급진적인", "rage": "분노", "raid": "습격", "railway": "철도",
        "raise": "들어 올리다, 기르다", "random": "무작위의", "range": "범위", "rank": "계급, 등급을 매기다",
        "rapid": "빠른", "rare": "드문", "rash": "성급한, 발진", "ratify": "승인하다",
        "ratio": "비율", "rational": "이성적인", "raw": "날것의, 가공하지 않은", "react": "반응하다",
        "readily": "기꺼이, 손쉽게", "realize": "깨닫다, 실현하다", "realm": "영역, 범위", "reap": "거두다, 수확하다",
        "rear": "뒤쪽의, 기르다", "reason": "이유, 이성", "reassure": "안심시키다", "rebel": "반역자, 반항하다",
        "recall": "회상하다, 리콜하다", "recede": "물러나다", "receipt": "영수증", "receive": "받다",
        "recent": "최근의", "reception": "환영회, 수신", "recess": "휴식", "recipe": "요리법",
        "recipient": "수령인", "reckless": "무모한", "reckon": "계산하다, 생각하다", "reclaim": "되찾다, 개간하다",
        "recognize": "인정하다, 알아보다", "recoil": "주춤하다, 반동", "recollect": "기억해내다", "recommend": "추천하다",
        "reconcile": "화해시키다", "reconstruct": "재건하다", "record": "기록하다", "recover": "회복하다",
        "recruit": "모집하다", "rectify": "수정하다, 고치다", "recycle": "재활용하다", "redeem": "보완하다, 되찾다",
        "reduce": "줄이다", "redundant": "불필요한, 중복된", "refer": "참조하다, 언급하다", "refine": "정제하다, 개선하다",
        "reflect": "반영하다, 반사하다", "reform": "개혁하다", "refrain": "삼가다", "refresh": "상쾌하게 하다",
        "refrigerator": "냉장고", "refuge": "피난(처)", "refund": "환불", "refuse": "거절하다",
        "refute": "반박하다", "regard": "간주하다, 존경", "regardless": "~에 상관없이", "regime": "정권, 체제",
        "region": "지역", "register": "등록하다", "regret": "후회하다", "regular": "정기적인",
        "regulate": "규제하다, 조절하다", "rehabilitate": "재활하다, 복원하다", "rehearse": "연습하다", "reign": "통치하다",
        "reinforce": "강화하다", "reject": "거절하다", "rejoice": "기뻐하다", "relate": "관련시키다",
        "relative": "상대적인, 친척", "relax": "휴식을 취하다", "relay": "중계하다", "release": "석방하다, 발표하다",
        "relentless": "끈질긴, 가차 없는", "relevant": "관련된", "reliable": "믿을 수 있는", "relief": "안도, 구호",
        "relieve": "완화하다", "religion": "종교", "relinquish": "포기하다", "relish": "즐기다, 풍미",
        "reluctant": "꺼리는", "rely": "의지하다", "remain": "남아 있다", "remarkable": "놀라운",
        "remedy": "치료(약), 해결책", "remind": "상기시키다", "reminisce": "추억하다", "remit": "송금하다, 면제하다",

        # [1601-1700] S 그룹: 과학, 사회, 상태 관련
        "sacred": "신성한", "sacrifice": "희생하다", "sadness": "슬픔", "safe": "안전한, 금고",
        "sake": "이익, 목적", "salary": "급여", "sanction": "제재, 허가", "sanctuary": "피난처, 보호구역",
        "sarcastic": "비꼬는, 풍자적인", "satisfy": "만족시키다", "savage": "야만적인, 사나운", "save": "구하다, 절약하다",
        "scale": "규모, 저울, 비늘", "scanty": "부족한", "scarce": "부족한, 드문", "scare": "겁주다",
        "scatter": "흩뿌리다", "scenery": "풍경", "scent": "향기", "schedule": "일정",
        "scheme": "계획, 책략", "scholar": "학자", "science": "과학", "scold": "꾸짖다",
        "scope": "범위, 시야", "scorn": "경멸하다", "scratch": "긁다", "screen": "화면, 가리다",
        "script": "대본, 글씨", "scrutiny": "정밀 조사", "sculpture": "조각", "seal": "인장, 봉인하다",
        "search": "찾다", "season": "계절, 양념하다", "secondary": "이차적인, 부수적인", "secret": "비밀",
        "section": "부분, 구역", "sector": "부문, 영역", "secular": "세속적인", "secure": "안전한, 확보하다",
        "sediment": "침전물", "seed": "씨앗", "seek": "찾다, 추구하다", "seem": "~처럼 보이다",
        "segment": "부분, 조각", "seize": "붙잡다", "seldom": "좀처럼 ~않는", "select": "선택하다",
        "selfish": "이기적인", "semester": "학기", "semi": "반, 어느 정도", "senate": "상원",
        "send": "보내다", "senior": "상급의, 선배", "sensation": "감각, 느낌, 선풍적 반응", "sensible": "분별 있는",
        "sensitive": "민감한", "sentence": "문장, 선고", "sentiment": "감정, 정서", "separate": "분리하다",
        "sequence": "순서, 배열", "serene": "고요한, 평온한", "series": "연속, 시리즈", "serious": "심각한, 진지한",
        "sermon": "설교", "serve": "봉사하다, 제공하다", "service": "봉사, 서비스", "session": "시간, 회기",
        "set": "놓다, 설정하다", "settle": "해결하다, 정착하다", "severe": "심각한, 가혹한", "shabby": "허름한",
        "shade": "그늘", "shadow": "그림자", "shake": "흔들다", "shallow": "얕은",
        "shame": "부끄러움", "shape": "모양, 형성하다", "share": "공유하다, 주식", "sharp": "날카로운",
        "shatter": "산산이 부서지다", "shed": "흘리다, 벗다", "sheer": "순전한, 가파른", "shelf": "선반",
        "shell": "껍질", "shelter": "피난처, 보호하다", "shift": "변화, 이동하다", "shine": "빛나다",
        "ship": "배, 수송하다", "shiver": "떨다", "shock": "충격", "shortage": "부족",
        "shortcut": "지름길", "shout": "외치다", "shove": "밀치다", "show": "보여주다",
        "shrewd": "영민한, 빈틈없는", "shrink": "줄어들다", "shrug": "으쓱하다", "shun": "피하다",
        # [1701-1800] T-U 그룹: 기술, 도구, 우주, 보편성
        "tackle": "다루다, 씨름하다", "tact": "재치, 요령", "tactic": "전략, 전술", "talent": "재능",
        "tame": "길들이다, 유순한", "tangible": "유형의, 실재하는", "target": "목표, 대상", "task": "과업, 일",
        "tease": "괴롭히다, 놀리다", "technical": "기술적인", "tedious": "지루한", "temper": "성질, 기분",
        "temperament": "기질, 성품", "temperate": "온화한, 절제하는", "temporary": "일시적인", "tempt": "유혹하다",
        "tend": "~하는 경향이 있다", "tendency": "경향, 추세", "tender": "부드러운, 입찰하다", "tense": "긴장한, 시제",
        "terminal": "끝의, 종점", "terminate": "종결시키다", "terrible": "끔찍한", "terrific": "아주 좋은, 멋진",
        "territory": "영토, 구역", "testify": "증언하다, 증명하다", "texture": "감촉, 질감", "theme": "주제, 테마",
        "theory": "이론", "therapy": "치료, 요법", "thereby": "그렇게 함으로써", "therefore": "그러므로",
        "thorough": "철저한", "thoughtful": "사려 깊은", "threat": "위협", "threshold": "문턱, 한계점",
        "thrive": "번창하다", "throne": "왕좌", "throughout": "도처에, 내내", "thrust": "밀다, 찌르다",
        "tidy": "깔끔한", "tight": "단단한, 꽉 조이는", "timid": "소심한", "tiny": "아주 작은",
        "tissue": "조직, 화장지", "title": "제목, 자격", "tolerance": "관용, 인내", "tolerate": "참다, 견디다",
        "toll": "통행료, 희생자 수", "topic": "주제", "torch": "횃불, 손전등", "torment": "고통, 괴롭히다",
        "torrent": "급류, 억수", "torture": "고문", "total": "전체의", "touch": "만지다, 감동시키다",
        "tough": "거친, 강인한", "toxic": "독성의", "trace": "추적하다, 흔적", "track": "길, 추적하다",
        "tradition": "전통", "tragedy": "비극", "trail": "오솔길, 흔적", "trait": "특성, 특징",
        "traitor": "배신자", "trample": "짓밟다", "tranquil": "고요한", "transact": "거래하다",
        "transcend": "초월하다", "transfer": "이동하다, 갈아타다", "transform": "변형시키다", "transient": "일시적인",
        "translate": "번역하다", "transmit": "전송하다, 전염시키다", "transparent": "투명한, 명백한", "transport": "운송하다",
        "trap": "함정", "tread": "밟다, 걷다", "treasure": "보물, 소중히 하다", "treat": "대우하다, 치료하다",
        "treaty": "조약", "tremble": "떨다", "tremendous": "엄청난", "trend": "경향, 추세",
        "trial": "시도, 재판", "tribe": "부족", "tribute": "찬사, 공물", "trick": "속임수",
        "trigger": "유발하다, 방어쇠", "trim": "다듬다", "triumph": "승리", "trivial": "사소한",
        "troop": "군대, 무리", "tropical": "열대의", "trouble": "문제", "true": "진실한",
        "trust": "신뢰", "truth": "진실", "tuition": "수업료", "tumble": "굴러 떨어지다",
        "turbulent": "격동의, 사나운", "tutor": "가정교사", "twilight": "황혼", "twist": "비틀다",
        "ultimate": "궁극적인", "umpire": "심판", "unanimous": "만장일치의", "unbearable": "참을 수 없는",

        # [1801-1900] V-W 그룹: 가치, 변화, 의지 관련
        "uncertain": "불확실한", "unconscious": "무의식적인", "undergo": "겪다, 경험하다", "undergraduate": "대학생",
        "underline": "밑줄을 긋다, 강조하다", "underlie": "~의 기저가 되다", "undermine": "약화시키다", "understand": "이해하다",
        "undertake": "맡다, 착수하다", "unemployment": "실업", "unfold": "펼치다", "unify": "통합하다",
        "unique": "독특한", "unite": "결합하다", "universal": "보편적인", "universe": "우주",
        "unlikely": "~할 것 같지 않은", "unprecedented": "전례 없는", "unreliable": "신뢰할 수 없는", "uphold": "지지하다, 유지하다",
        "upright": "똑바른", "uproot": "뿌리째 뽑다", "upset": "당황한, 뒤엎다", "urban": "도시의",
        "urge": "촉구하다, 충동", "urgent": "긴급한", "usage": "사용(법)", "use": "사용하다",
        "utensil": "기구, 도구", "utilize": "이용하다", "utmost": "최선의, 극도의", "utter": "발언하다, 완전한",
        "vacant": "비어 있는", "vague": "모호한", "vain": "헛된, 자만심이 강한", "valid": "유효한, 타당한",
        "valley": "계곡", "valuable": "가치 있는", "value": "가치", "vanish": "사라지다",
        "vanity": "허영심", "variable": "변하기 쉬운, 변수", "variation": "변화, 차이", "variety": "다양성",
        "various": "다양한", "vary": "다르다, 바뀌다", "vast": "광대한", "vault": "금고, 도약",
        "vegetable": "채소", "vehicle": "탈것, 매개체", "veil": "베일, 가리다", "velocity": "속도",
        "venerable": "공경할 만한", "vengeance": "복수", "venture": "모험, 벤처", "verbal": "말의, 구두의",
        "verdict": "평결, 판단", "verify": "증명하다, 확인하다", "versatile": "다재다능한", "version": "판, 버전",
        "vertical": "수직의", "vessel": "선박, 혈관, 그릇", "veteran": "베테랑, 퇴역 군인", "veto": "거부권",
        "via": "~을 통하여", "vibrate": "진동하다", "vibrant": "활기찬", "vice": "악덕",
        "vicious": "사악한", "victim": "희생자", "victory": "승리", "view": "견해, 관점",
        "vigorous": "활기찬, 격렬한", "village": "마을", "violate": "위반하다", "violence": "폭력",
        "virtual": "가상의, 사실상의", "virtue": "미덕, 장점", "visible": "보이는", "vision": "시력, 미래상",
        "visit": "방문하다", "visual": "시각의", "vital": "필수적인, 활기찬", "vivid": "생생한",
        "vocation": "천직, 직업", "voice": "목소리", "void": "빈 공간, 무효의", "volcano": "화산",
        "volume": "부피, 음량, 권", "voluntary": "자발적인", "volunteer": "자원봉사자", "vote": "투표",
        "vow": "맹세", "voyage": "항해", "vulnerable": "취약한", "wage": "임금, 전쟁을 벌이다",
        "wait": "기다리다", "waive": "포기하다, 철회하다", "wake": "깨다", "wander": "헤매다",

        # [1901-2000] 마지막 100개: 고난도 형용사 & 최종 마무리
        "want": "원하다, 결핍", "ward": "병동, 구역", "warehouse": "창고", "warm": "따뜻한",
        "warn": "경고하다", "warrant": "영장, 정당화하다", "waste": "낭비하다", "watch": "지켜보다",
        "water": "물, 물을 주다", "wave": "파도, 흔들다", "wax": "왁스, 커지다", "weak": "약한",
        "wealth": "부, 재산", "weapon": "무기", "wear": "입다, 닳다", "weary": "지친",
        "weave": "짜다, 엮다", "wedding": "결혼식", "weed": "잡초", "weep": "울다",
        "weigh": "무게를 달다, 숙고하다", "weight": "무게", "weird": "이상한", "welfare": "복지",
        "well": "잘, 우물", "wet": "젖은", "wheat": "밀", "wheel": "바퀴, 핸들",
        "whereas": "~인 반면에", "whereby": "그것에 의하여", "while": "~하는 동안, ~인 반면에", "whip": "채찍질하다",
        "whisper": "속삭이다", "whistle": "휘파람", "whole": "전체의", "wholesome": "건강에 좋은",
        "wicked": "사악한", "wide": "넓은", "widespread": "널리 퍼진", "widow": "미망인",
        "width": "너비", "wield": "휘두르다, 행사하다", "wild": "야생의", "will": "의지, 유언장",
        "willing": "기꺼이 ~하는", "win": "이기다, 얻다", "wind": "바람, 감다", "wisdom": "지혜",
        "wise": "현명한", "wish": "바라다", "wit": "재치, 기지", "withdraw": "철회하다, 인출하다",
        "wither": "시들다", "withhold": "보류하다, 주지 않다", "within": "~이내에", "withstand": "견디다, 저항하다",
        "witness": "목격자, 증언하다", "woe": "비통, 괴로움", "wonder": "궁금해하다, 경이", "wood": "나무, 숲",
        "wool": "양모", "word": "단어, 약속", "work": "일하다, 작품", "world": "세계",
        "worry": "걱정하다", "worship": "예배하다, 숭배하다", "worth": "가치가 있는", "worthy": "가치 있는",
        "wound": "상처", "wrap": "싸다, 포장하다", "wrath": "분노", "wreck": "난파, 망가뜨리다",
        "wrestle": "레슬링하다, 싸우다", "wretched": "비참한", "wrinkle": "주름", "write": "쓰다",
        "wrong": "틀린", "x-ray": "엑스레이", "yard": "마당, 야드", "yawn": "하품하다",
        "year": "해, 년", "yearn": "갈망하다", "yell": "소리지르다", "yellow": "노란색",
        "yield": "산출하다, 양보하다", "young": "젊은", "youth": "젊음, 청춘", "zeal": "열의, 열정",
        "zenith": "정점, 천장", "zero": "영", "zone": "지역, 구역", "zoo": "동물원",
    }
    }
    # [중복 제거 로직] 단어(Key)가 중복되면 마지막에 적힌 것만 남깁니다.
    st.session_state.voca_db = raw_data

# --- 2. 퀴즈 세션 초기화 ---
if 'quiz_list' not in st.session_state:
    all_words = list(st.session_state.voca_db.items())
    # 20개를 뽑기 전에 한 번 섞어줍니다.
    random.shuffle(all_words)
    sample_count = min(len(all_words), 20)
    st.session_state.quiz_list = all_words[:sample_count]
    st.session_state.total_count = sample_count
    st.session_state.show_answer = False

st.title("🎯 수능 단어 완전 정복")

# ... (중략: 성공 화면 및 UI 구성) ...

if st.session_state.quiz_list:
    word, mean = st.session_state.quiz_list[0]
    
    # [중복 방지 핵심] 남은 문제 수 표시
    st.write(f"현재 단어 포함 총 **{len(st.session_state.quiz_list)}**개 남음")
    
    # ... (정답 입력 UI 부분) ...

    if st.session_state.show_answer:
        st.error(f"❌ 정답은: **{mean}**")
        if st.button("외웠어요! 다음 문제 ➡️"):
            # 틀린 문제를 맨 뒤로 보냅니다.
            wrong_item = st.session_state.quiz_list.pop(0)
            st.session_state.quiz_list.append(wrong_item)
            
            # [중복 방지] 만약 남은 문제가 2개 이상이면, 
            # 방금 틀린 게 바로 나오지 않도록 두 번째 단어부터 끝까지만 섞습니다.
            if len(st.session_state.quiz_list) > 1:
                sub_list = st.session_state.quiz_list[1:]
                random.shuffle(sub_list)
                st.session_state.quiz_list = [st.session_state.quiz_list[0]] + sub_list
            
            st.session_state.show_answer = False
            st.rerun()
